# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/checkoutservice/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  DockerImageName: 'sit-sandbox7-sb/microservices-demo/checkoutservice'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

      - task: Docker@2
        inputs:
          containerRegistry: 'Google Container Registry'
          repository: $(DockerImageName)
          command: 'buildAndPush'
          Dockerfile: './src/checkoutservice/Dockerfile'
          tags: |
            $(Build.BuildId)
            latest

      - task: CmdLine@1
        displayName: 'Lock image version in deployment.yaml'
        inputs:
          filename: /bin/bash
          workingFolder: ./src/checkoutservice/
          arguments: '-c "awk ''{gsub(\"CHECKOUTSERVICE_IMAGE\", \"eu.gcr.io/$(DockerImageName):$(Build.BuildId)\", $0); print}'' checkoutservice.yaml > $(build.artifactstagingdirectory)/checkoutservice.yaml"'

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'AdserviceDeployment'
          publishLocation: 'Container'
